language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova@sha256:3f267e76636f8d7cfcd04d02550236cd2aaa17c431cda7e7e7b982acd4b9146b

    - os: osx
      osx_image: xcode8.3
      before_script: sudo npm install -g cordova
      sudo: required
      install:
        - brew update &> /dev/null
        - brew upgrade &> /dev/null
        - brew install node swig coreutils gnu-sed automake autoconf pkg-config &> /dev/null
        - pip2 install virtualenv
      script:
        - ./prepare.sh
        - cordova prepare ios
        - cordova build ios

